"""Initial models

Revision ID: a3aa27ff4b02
Revises: 
Create Date: 2026-04-12 18:28:39.236270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3aa27ff4b02'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_cache',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('data_snapshot_id', sa.String(length=100), nullable=True),
    sa.Column('prediction_team_a_win', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('detailed_analysis', sa.Text(), nullable=True),
    sa.Column('key_matchups', sa.JSON(), nullable=True),
    sa.Column('map_predictions', sa.JSON(), nullable=True),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_cache_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_cache_match_id'), ['match_id'], unique=False)
        batch_op.create_index('ix_analysis_cache_match_type', ['match_id', 'analysis_type'], unique=False)

    op.create_table('players',
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('current_team_id', sa.Integer(), nullable=True),
    sa.Column('current_team_name', sa.String(length=100), nullable=True),
    sa.Column('faceit_elo', sa.Integer(), nullable=True),
    sa.Column('faceit_skill_level', sa.Integer(), nullable=True),
    sa.Column('faceit_kd_30d', sa.Float(), nullable=True),
    sa.Column('faceit_adr_30d', sa.Float(), nullable=True),
    sa.Column('faceit_winrate_30d', sa.Float(), nullable=True),
    sa.Column('faceit_matches_30d', sa.Integer(), nullable=True),
    sa.Column('faceit_last_updated', sa.Date(), nullable=True),
    sa.Column('official_total_matches', sa.Integer(), nullable=True),
    sa.Column('official_avg_kd', sa.Float(), nullable=True),
    sa.Column('official_avg_adr', sa.Float(), nullable=True),
    sa.Column('official_avg_rating', sa.Float(), nullable=True),
    sa.Column('official_last_updated', sa.Date(), nullable=True),
    sa.Column('bone_score', sa.Float(), nullable=True),
    sa.Column('true_rating', sa.Float(), nullable=True),
    sa.Column('form_trend', sa.String(length=20), nullable=True),
    sa.Column('consistency_index', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index('ix_players_active_score', ['is_active', 'bone_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_bone_score'), ['bone_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_current_team_id'), ['current_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_nickname'), ['nickname'], unique=True)
        batch_op.create_index('ix_players_nickname_active', ['nickname', 'is_active'], unique=False)

    op.create_table('teams',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('world_ranking', sa.Integer(), nullable=True),
    sa.Column('ranking_points', sa.Integer(), nullable=True),
    sa.Column('ranking_change', sa.Integer(), nullable=True),
    sa.Column('total_matches', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('team_synergy_score', sa.Float(), nullable=True),
    sa.Column('momentum_score', sa.Float(), nullable=True),
    sa.Column('current_roster', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index('ix_teams_active_ranking', ['is_active', 'world_ranking'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_teams_world_ranking'), ['world_ranking'], unique=False)

    op.create_table('matches',
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('team_a_id', sa.Integer(), nullable=True),
    sa.Column('team_b_id', sa.Integer(), nullable=True),
    sa.Column('team_a_score', sa.Integer(), nullable=True),
    sa.Column('team_b_score', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('tournament_name', sa.String(length=200), nullable=True),
    sa.Column('tournament_tier', sa.String(length=10), nullable=True),
    sa.Column('format', sa.Enum('BO1', 'BO3', 'BO5', name='matchformat'), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'LIVE', 'FINISHED', 'CANCELLED', name='matchstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('maps_played', sa.String(length=500), nullable=True),
    sa.Column('vod_url', sa.String(length=500), nullable=True),
    sa.Column('prize_pool', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_matches_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_status'), ['status'], unique=False)
        batch_op.create_index('ix_matches_status_scheduled', ['status', 'scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_team_a_id'), ['team_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_team_b_id'), ['team_b_id'], unique=False)
        batch_op.create_index('ix_matches_teams', ['team_a_id', 'team_b_id'], unique=False)

    op.create_table('metric_snapshots',
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('bone_score', sa.Float(), nullable=True),
    sa.Column('true_rating', sa.Float(), nullable=True),
    sa.Column('form_trend', sa.String(length=20), nullable=True),
    sa.Column('faceit_elo', sa.Integer(), nullable=True),
    sa.Column('official_rating_20', sa.Float(), nullable=True),
    sa.Column('official_rating_5', sa.Float(), nullable=True),
    sa.Column('adr_30d', sa.Float(), nullable=True),
    sa.Column('kd_30d', sa.Float(), nullable=True),
    sa.Column('world_ranking', sa.Integer(), nullable=True),
    sa.Column('team_synergy', sa.Float(), nullable=True),
    sa.Column('win_rate_30d', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_metric_snapshots_entity_date', ['entity_type', 'entity_id', 'snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_snapshots_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index('ix_metric_snapshots_player_date', ['player_id', 'snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_snapshots_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index('ix_metric_snapshots_team_date', ['team_id', 'snapshot_date'], unique=False)

    op.create_table('historical_predictions',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_a_id', sa.Integer(), nullable=False),
    sa.Column('team_b_id', sa.Integer(), nullable=False),
    sa.Column('team_a_name', sa.String(length=100), nullable=False),
    sa.Column('team_b_name', sa.String(length=100), nullable=False),
    sa.Column('predicted_winner_id', sa.Integer(), nullable=True),
    sa.Column('predicted_team_a_win_prob', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('team_a_bone_score_avg', sa.Float(), nullable=True),
    sa.Column('team_b_bone_score_avg', sa.Float(), nullable=True),
    sa.Column('team_a_ranking', sa.Integer(), nullable=True),
    sa.Column('team_b_ranking', sa.Integer(), nullable=True),
    sa.Column('input_data_snapshot', sa.JSON(), nullable=True),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('analysis_text', sa.Text(), nullable=True),
    sa.Column('actual_winner_id', sa.Integer(), nullable=True),
    sa.Column('actual_team_a_score', sa.Integer(), nullable=True),
    sa.Column('actual_team_b_score', sa.Integer(), nullable=True),
    sa.Column('was_upset', sa.Boolean(), nullable=True),
    sa.Column('prediction_correct', sa.Boolean(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historical_predictions', schema=None) as batch_op:
        batch_op.create_index('ix_historical_predictions_correct', ['prediction_correct'], unique=False)
        batch_op.create_index('ix_historical_predictions_match', ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_predictions_match_id'), ['match_id'], unique=False)
        batch_op.create_index('ix_historical_predictions_predicted_at', ['predicted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_predictions_team_a_id'), ['team_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_predictions_team_b_id'), ['team_b_id'], unique=False)

    op.create_table('player_match_stats',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('map_name', sa.String(length=50), nullable=True),
    sa.Column('map_number', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('adr', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('kast', sa.Float(), nullable=True),
    sa.Column('impact', sa.Float(), nullable=True),
    sa.Column('headshot_percent', sa.Float(), nullable=True),
    sa.Column('utility_damage', sa.Float(), nullable=True),
    sa.Column('first_kills', sa.Integer(), nullable=True),
    sa.Column('first_deaths', sa.Integer(), nullable=True),
    sa.Column('clutches_won', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'match_id', 'map_name', name='uq_player_match_map')
    )
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_match_stats_match_id'), ['match_id'], unique=False)
        batch_op.create_index('ix_player_match_stats_match_player', ['match_id', 'player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_match_stats_player_id'), ['player_id'], unique=False)
        batch_op.create_index('ix_player_match_stats_player_rating', ['player_id', 'rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_match_stats_rating'), ['rating'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_match_stats_rating'))
        batch_op.drop_index('ix_player_match_stats_player_rating')
        batch_op.drop_index(batch_op.f('ix_player_match_stats_player_id'))
        batch_op.drop_index('ix_player_match_stats_match_player')
        batch_op.drop_index(batch_op.f('ix_player_match_stats_match_id'))

    op.drop_table('player_match_stats')
    with op.batch_alter_table('historical_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_predictions_team_b_id'))
        batch_op.drop_index(batch_op.f('ix_historical_predictions_team_a_id'))
        batch_op.drop_index('ix_historical_predictions_predicted_at')
        batch_op.drop_index(batch_op.f('ix_historical_predictions_match_id'))
        batch_op.drop_index('ix_historical_predictions_match')
        batch_op.drop_index('ix_historical_predictions_correct')

    op.drop_table('historical_predictions')
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_metric_snapshots_team_date')
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_snapshot_date'))
        batch_op.drop_index('ix_metric_snapshots_player_date')
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_entity_id'))
        batch_op.drop_index('ix_metric_snapshots_entity_date')

    op.drop_table('metric_snapshots')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index('ix_matches_teams')
        batch_op.drop_index(batch_op.f('ix_matches_team_b_id'))
        batch_op.drop_index(batch_op.f('ix_matches_team_a_id'))
        batch_op.drop_index('ix_matches_status_scheduled')
        batch_op.drop_index(batch_op.f('ix_matches_status'))
        batch_op.drop_index(batch_op.f('ix_matches_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_matches_external_id'))

    op.drop_table('matches')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_world_ranking'))
        batch_op.drop_index(batch_op.f('ix_teams_name'))
        batch_op.drop_index(batch_op.f('ix_teams_is_active'))
        batch_op.drop_index('ix_teams_active_ranking')

    op.drop_table('teams')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index('ix_players_nickname_active')
        batch_op.drop_index(batch_op.f('ix_players_nickname'))
        batch_op.drop_index(batch_op.f('ix_players_is_active'))
        batch_op.drop_index(batch_op.f('ix_players_current_team_id'))
        batch_op.drop_index(batch_op.f('ix_players_bone_score'))
        batch_op.drop_index('ix_players_active_score')

    op.drop_table('players')
    with op.batch_alter_table('analysis_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_analysis_cache_match_type')
        batch_op.drop_index(batch_op.f('ix_analysis_cache_match_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_cache_expires_at'))

    op.drop_table('analysis_cache')
    # ### end Alembic commands ###
