"""Initial models

Revision ID: ab4edaf4ff10
Revises: a3aa27ff4b02
Create Date: 2026-04-13 05:32:00.208771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4edaf4ff10'
down_revision: Union[str, Sequence[str], None] = 'a3aa27ff4b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peak_ranking', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('carry_dependency', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_roster_json', sa.Text(), nullable=True))
        batch_op.create_index('ix_teams_name_active', ['name', 'is_active'], unique=False)
        batch_op.drop_column('current_roster')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_roster', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_index('ix_teams_name_active')
        batch_op.drop_column('current_roster_json')
        batch_op.drop_column('carry_dependency')
        batch_op.drop_column('peak_ranking')

    # ### end Alembic commands ###
